all:
	@echo "Ejecutando con fichero prueba.txt"
	python3 cliserv2.py prueba.txt

binary:
	@echo "Ejecutando con fichero /boot/vmlinuz.old"
	python3 cliserv2.py /boot/vmlinuz

services:
	@echo "Ejecutando con fichero /etc/services"
	python3 cliserv2.py /etc/services

clean:
	@echo "Limpiando..."
